title: Streamdata Gallery
url: aws-workspaces.api.streamdata.gallery
tag: AWS WorkSpaces
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery-organizations
github_repo: aws-workspaces
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
